### ISSUE TITLE
Investigate XSS

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#20]
With the capability of tracking a session #7 can we return injected malicious code to the attacker?

```
POST /posts?comment=<script>alert('xss');</script>
GET /posts contains the JS
```

**Comment by glaslos** [comment]
Moved this issue to gsoc_sprint_3

**Comment by afeena** [comment]
In Google chrome and Mozilla firefox we can get xss only in post requests (because of replacing <> and ' in these browsers ), that's why I think about this structure:
- SNARE get post request with xss and send post_data in data to TANNER 
- TANNER browses post_data and check the data with this pattern '<(.|\n)*?>' 
- If we have xss, TANNER send to SNARE result with payload, where payload = xss script 

Next I think about two ways: 
- respond to the user with script and content type html, it will be a blank page with xss  
- we can get previous page from session and inject xss in this page, so we will have a normal page with having injected script

**Comment by glaslos** [comment]
This sounds really good. You can test this by commenting on the blog posts.

**Comment by afeena** [comment]
When we inject script into page in Google chrome, we have next error: 

"token contains a reflected xss vector"
http://i.imgur.com/9QpAO7o.png 

I tested alerts in Mozilla and it's work correcly

**Comment by glaslos** [comment]
Ah, interesting, can you disable the security check in chrome?

**Comment by afeena** [comment]
It's possible if start Chrome with --disable-web-security flag

**Comment by glaslos** [comment]
Do you think we can close this after I merged 27af9da ?

**Comment by afeena** [comment]
I think it's a big task and we can hold this issue open some time to look what more we can do with it

**Comment by glaslos** [comment]
Okay, I will then just remove the milestone.

**Comment by rnehra01** [comment]
https://github.com/mushorg/tanner/issues/20#issuecomment-225129836
^^ What do we need to achieve? DO we need to bypass Chrome XSS Auditor?

**Comment by nsmfoo** [comment]
Hi, 

I think this subject might suffer from some misunderstandings (or maybe it's me that missing something) =)

Chrome, IE do have some built in XSS protection. This is also why "people" tend to use Firefox when performing application assessments, this was noted earlier in the thread.  Other common ways is to utilise a vulnerability scanner, that "just" (there are of course variants that instrument a real browser) look for the presence off the inserted javascript in the response data to see if the XSS succeeded 

So in short, having a working XSS emulator should not really have to take into consideration what the requester is running, that being said Snare/Tanner do reflect the javascript code inserted nicely, so this might just be an old thread?

**Comment by afeena** [comment]
@nsmfoo I think you are right, we can close this issue and in case of any other questions we will create new one :)
